ARG PYTORCH="2.1.0"
ARG CUDA="11.8"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ARG DEBIAN_FRONTEND=noninteractive

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

# To fix GPG key error when running apt-get update
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub


RUN apt-get update && apt-get install -y wget git nano 

RUN apt-get install -y  libglib2.0-0 libsm6 libxrender-dev libxext6 libgl1-mesa-glx

RUN git clone https://github.com/JunkyByte/easy_ViTPose.git \
&& cd easy_ViTPose/ \
&& pip install -e . \
&& pip install -r requirements.txt \
&& pip install huggingface_hub && pip install jupyter \
&& pip install scikit-learn && pip install matplotlib \
&& pip install ifcopenshell==0.7.0.240423 \
&& pip install imutils
